try {
    console.log("In try block");
} catch (e) {
    console.log("In catch block");
}
